import { Button } from '../components/ui/button';
import { Link } from "react-router-dom";
import { aboutReviews, site } from "../data";

export default function About() {
  return <main id="main-content" className="page page-top about-page">
    <section className="about-intro"><div><p className="eyebrow">About ProGear Mats</p><h1 className="page-title">The right mat<br /><span>changes the cabin.</span></h1></div><div className="about-copy"><p>ProGear Mats makes premium custom-fit car mats for drivers who want a cleaner, better-finished cabin without guessing which pattern will work.</p><p>Our fitment library is built around real vehicle photos. Share your car details and the team will help confirm the right 7D or 9D option for your drive.</p><Button asChild className="about-shop-button"><Link to="/shop">Shop mats <span aria-hidden="true">↗</span></Link></Button></div></section>
    <section className="visit-card"><div className="visit-copy"><p className="eyebrow">Visit the shop</p><h2 className="section-title">See the finish<br />in person.</h2><div className="contact-facts"><p>{site.address}</p>{site.hours && <p>{site.hours}</p>}<a href={`tel:${site.whatsapp}`}>{site.phone}</a></div><Button asChild><a href={site.mapLink} target="_blank" rel="noreferrer">Open in Google Maps <span aria-hidden="true">↗</span></a></Button></div><iframe title="ProGear Mats location" src={site.map} loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></section>
    <section className="about-reviews" aria-labelledby="about-reviews-title"><div className="section-heading"><div><p className="eyebrow">From Google</p><h2 className="section-title" id="about-reviews-title">Customer reviews.</h2></div><a className="text-link" href={site.googleReviews} target="_blank" rel="noreferrer">See all reviews <span aria-hidden="true">↗</span></a></div><div className="about-review-grid">{aboutReviews.map(review => <a className="about-review-card" href={review.link} target="_blank" rel="noreferrer" key={review.link}><div className="about-review-head"><span className="about-review-avatar" aria-hidden="true">{review.initials}{review.avatar && <img src={review.avatar} alt="" loading="lazy" referrerPolicy="no-referrer" onError={event => { event.currentTarget.style.display = "none"; }} />}</span><span><strong>{review.name}</strong><small>{review.when} · Google review</small></span><b aria-hidden="true">↗</b></div><div className="about-review-stars" aria-label="5 out of 5 stars">★★★★★</div><blockquote>“{review.quote}”</blockquote></a>)}</div></section>
  </main>;
}
