import { Link } from 'react-router-dom';
import { money } from '../catalog';
import Icon from '../components/Icon';
import { whatsappUrl } from '../data';
export default function Cart() {
  const items = JSON.parse(localStorage.getItem('progear-cart') || '[]');
  const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const message = items.map(item => `${item.name} (${item.type}), ${item.category}, ${item.seats}-seater, ${item.colour || 'standard colour'}, qty ${item.quantity} — ${money(item.price)}`).join('\n');
  return <main className="page page-top cart-page"><div className="page-intro"><p className="eyebrow">Your selection</p><h1 className="page-title">Your <span>cart.</span></h1><p className="page-lede">Review your chosen mats, then send the configuration to ProGear on WhatsApp to confirm fitment and delivery.</p></div>{items.length ? <div className="cart-layout"><div className="cart-list">{items.map(item => <article className="cart-item" key={item.key}><img src={item.image} alt="" /><div><h2>{item.name}</h2><p>{item.type} · {item.category} · {item.seats}-seater<br />{item.colour || 'Standard finish'}</p><div className="cart-item-actions"><span>Qty {item.quantity}</span><button className="remove-item" onClick={() => { const next = items.filter(x => x.key !== item.key); localStorage.setItem('progear-cart', JSON.stringify(next)); window.location.reload(); }}>Remove</button></div></div><strong>{money(item.price * item.quantity)}</strong></article>)}</div><aside className="order-summary"><h2>Order summary</h2><div className="summary-line"><span>Subtotal</span><strong>{money(total)}</strong></div><div className="summary-line"><span>Shipping</span><strong>Free</strong></div><div className="summary-line total"><span>Total</span><strong>{money(total)}</strong></div><a className="button red wide" href={whatsappUrl(`Hi ProGear Mats, I want to confirm my cart:\n${message}\nTotal: ${money(total)}`)} target="_blank" rel="noreferrer">Continue on WhatsApp <Icon name="arrow" /></a><p className="summary-note">The team will confirm your vehicle fitment and final delivery details before dispatch.</p></aside></div> : <div className="empty-state"><Icon name="bag" size={30} /><h2>Your cart is waiting.</h2><p>Choose a collection to start building your order.</p><Link className="button dark" to="/shop">Shop the collection <Icon name="arrow" /></Link></div>}</main>;
}
