import { site, whatsappUrl } from "../data";

export default function Contact() {
  const submit = event => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    window.open(whatsappUrl(`Hi ProGear Mats!\nName: ${data.get("name")}\nPhone: ${data.get("phone")}\nCar: ${data.get("car")}\nMessage: ${data.get("message")}`), "_blank", "noopener,noreferrer");
  };
  return <main className="page page-top contact-page"><section className="contact-intro"><div><p className="eyebrow">Talk to ProGear</p><h1 className="page-title">Your fitment<br /><span>starts here.</span></h1><p className="page-lede">Send your car details and the form will open WhatsApp with everything filled in.</p></div><div className="contact-links"><div><span>WhatsApp / phone</span><a href={`tel:${site.whatsapp}`}>{site.phone}</a></div><div><span>Email</span><a href={`mailto:${site.email}`}>{site.email}</a></div><div><span>Shop</span><p>{site.address}</p><a href={site.mapLink} target="_blank" rel="noreferrer">Open map ↗</a></div></div></section><form className="contact-form" onSubmit={submit}><div className="form-grid"><label>Your name<input className="field" name="name" required placeholder="Your name" /></label><label>Phone number<input className="field" name="phone" type="tel" required placeholder="+91 98765 43210" /></label></div><label>Car brand, model and year<input className="field" name="car" required placeholder="Hyundai Creta, 2024" /></label><label>What are you looking for?<textarea className="field" name="message" placeholder="7D or 9D mats, colour, fitment question..." /></label><button className="btn-primary" type="submit">Continue on WhatsApp <span aria-hidden="true">↗</span></button></form><section className="connect-strip"><div><p className="eyebrow">Follow along</p><h2 className="section-title">See new fitments<br />as they arrive.</h2></div><div className="qr-grid"><a className="qr-card" href={site.instagram} target="_blank" rel="noreferrer"><img src="/images/client/instagram-qr.png" alt="ProGear Mats Instagram QR code" loading="lazy" /><span>Instagram</span><strong>@insta_pro.gear ↗</strong></a><a className="qr-card" href={site.googleReviews} target="_blank" rel="noreferrer"><img src="/images/client/google-review-qr.png" alt="ProGear Mats Google Maps QR code" loading="lazy" /><span>Google Maps</span><strong>Visit our profile ↗</strong></a></div></section></main>;
}
